<?php

/**
 * @file
 * Big Blue Button - Enables universities and colleges to deliver a high-quality
 * learning experience.
 * 
 * @author
 * Stefan Auditor <stefan.auditor@erdfisch.de>
 */

/**
 * Implements hook_views_api().
 */
function bbb_views_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'bbb') . '/includes',
  );
}

/**
 * Implements hook_autoload_info().
 */
function bbb_views_autoload_info() {
  return array(
    'views_handler_field_bbb_join_attendee' => 'includes/views_handler_field_bbb_join_attendee.inc',
    'views_handler_field_bbb_join_moderator' => 'includes/views_handler_field_bbb_join_moderator.inc',
  );
}
